/*
 * The MIT License
 *
 * Copyright 2020 alexr.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package net.napilnik.jdateinterval.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import net.napilnik.jdateinterval.event.IntervalChangedListener;
import net.napilnik.jdateinterval.event.IntervalEvent;
import net.napilnik.jdateinterval.model.DateIntervalModel;
import net.napilnik.jdateinterval.model.DefaultDateIntervalModel;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author alexr
 */
public class JDateInterval extends javax.swing.JPanel implements IntervalChangedListener {

    private DateIntervalModel model;

    /**
     * Creates new form JDateInterval
     */
    public JDateInterval() {
        this(new DefaultDateIntervalModel());
    }

    public JDateInterval(DateIntervalModel model) {
        setModel(model);
        initComponents();
        initView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        startDate = new net.napilnik.jdateinterval.view.MyJDate();
        endDate = new net.napilnik.jdateinterval.view.MyJDate();

        jLabel1.setText("StartDate");

        jLabel2.setText("EndDate");

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(resetButton)
                    .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        getModel().reset();
    }//GEN-LAST:event_resetButtonActionPerformed

    public final void setModel(DateIntervalModel model) {
        this.model = model;
        this.model.addIntervalListener(this);
    }

    public final DateIntervalModel getModel() {
        return model;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private net.napilnik.jdateinterval.view.MyJDate endDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton resetButton;
    private net.napilnik.jdateinterval.view.MyJDate startDate;
    // End of variables declaration//GEN-END:variables

    @Override
    public void startDateChanged(IntervalEvent event) {
        final Date value = event.getNewValue();
        startDate.setDate(value);
    }

    @Override
    public void endDateChanged(IntervalEvent event) {
        final Date value = event.getNewValue();
        endDate.setDate(value);
    }

    public void setToolTipText(String startDateText, String endDateText) {
        startDate.setToolTipText(startDateText);
        endDate.setToolTipText(endDateText);
    }

    private void initView() {
        getModel().reset();

        startDate.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Object source = e.getSource();
                if (source instanceof JXDatePicker) {
                    model.setStartDate(((JXDatePicker) source).getDate());
                }
            }
        });
        
        endDate.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Object source = e.getSource();
                if (source instanceof JXDatePicker) {
                    model.setEndDate(((JXDatePicker) source).getDate());
                }
            }
        });

        startDate.addTodayClickListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                model.setStartDate(new Date());
                startDate.grabFocus();
            }
        });

        endDate.addTodayClickListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                model.setEndDate(new Date());
                endDate.grabFocus();
            }
        });
    }
}
